name: Trigger auto deployment for mcp-links

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/mcp-links-AutoDeployTrigger-50990fb5-be48-4371-939e-6c00f3306024.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.MCPLINKS_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.MCPLINKS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MCPLINKS_REGISTRY_PASSWORD }}
          containerAppName: mcp-links
          resourceGroup: mcp
          imageToBuild: ghcr.io/mcp-links:${{ github.sha }}
          
            

     

